cart/urls.py
from django.urls import path, include
from .views import cart_detail_view, add_to_cart_view,remove_from_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', remove_from_cart, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pages.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('products/', include('products.urls')),
                  path('rosetta/', include('rosetta.urls')),
                  path('cart/', include('cart.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('aboutus/', views.AboutUsPageView.as_view(), name='aboutus'),
]

products/urls.py
from django.urls import path, include

from .views import ProductListView, ProductDetailView, CommentCreateView

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('comment/<int:product_id>', CommentCreateView.as_view(), name='comment_create'),

]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

cart/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _


class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.PositiveIntegerField(default=0)
    active = models.BooleanField(default=True)
    image = models.ImageField(verbose_name=_('Product Image'), upload_to='product/product_cover/', blank=True)

    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.id])


class ActiveCommentsManager(models.Manager):
    def get_queryset(self):
        return super(ActiveCommentsManager, self).get_queryset().filter(active=True)


class Comment(models.Model):
    PRODUCT_STARS = [
        ('1', _('Very Bad')),
        ('2', _('Bad')),
        ('3', _('Normal')),
        ('4', _('Good')),
        ('5', _('Perfect')),
    ]

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Comment author'
    )
    body = models.TextField(verbose_name=_('Comment Text'))
    stars = models.CharField(max_length=10, choices=PRODUCT_STARS, verbose_name=_('What is your score !?'))

    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    active = models.BooleanField(default=True)

    # manager
    objects = models.Manager()
    active_comments_manager = ActiveCommentsManager()

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.product.id])

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)

cart/forms.py
from django import forms


class AddToCartProductForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 31)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

products/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body', 'stars', ]

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from products.models import Product
from django.views.decorators.http import require_POST
from .forms import AddToCartProductForm
from .cart import Cart


def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_quantity_form'] = AddToCartProductForm({
            'quantity': item['quantity'],
            'inplace': True,
        })

    return render(request, 'cart/cart_detail.html', {
        'cart': cart
    })


@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)
    form = AddToCartProductForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        cart.add(product, quantity, replace_current_quantity=cleaned_data['inplace'])

    return redirect('cart:cart_detail')


def remove_from_cart(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)

    cart.remove(product)

    return redirect('cart:cart_detail')

pages/views.py
from django.shortcuts import render

from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home.html'


class AboutUsPageView(TemplateView):
    template_name = 'pages/aboutus.html'

products/views.py
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.utils.translation import gettext as _

from .models import Product, Comment
from .forms import CommentForm


class ProductListView(generic.ListView):
    # model = Product
    queryset = Product.objects.filter(active=True)
    template_name = 'products/product_list.html'
    context_object_name = 'products'


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context


class CommentCreateView(generic.CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user

        product_id = int(self.kwargs['product_id'])
        product = get_object_or_404(Product, id=product_id)
        obj.product = product

        messages.success(self.request, _('Comment successfully created'))

        return super().form_valid(form)

cart/templates/cart/cart_detail.html
{% extends '_base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load comment_tags %}
{% load persian_translation_tags %}
{% load humanize %}

{% block content %}

    {% translate 'Cart' as header_name %}
    {% include 'topheader.html' with header_name=header_name %}

    <!-- Main Content Wrapper Start -->
    <div class="main-content-wrapper">
        <div class="page-content-inner ptb--80">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-md--50">
                        <div class="row no-gutters">
                            <div class="col-12">
                                {% if cart %}
                                    <div class="table-content table-responsive">
                                        <table class="table text-center">
                                            <thead>
                                            <tr>
                                                <th>&nbsp;</th>
                                                <th>عکس محصول</th>
                                                <th>نام محصول</th>
                                                <th>قیمت</th>
                                                <th>مقدار</th>
                                                <th>مجموع</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in cart %}
                                                <tr>
                                                    <td class="product-remove text-left">
                                                        <a href="{% url 'cart:cart_remove' item.product_obj.id %}">
                                                            <i class="flaticon flaticon-cross"></i>
                                                        </a>
                                                    </td>
                                                    <td class="product-thumbnail text-left">
                                                        <img src="{{ item.product_obj.image.url }}">
                                                    </td>
                                                    <td class="product-name">
                                                        <h3>
                                                            <a href="{{ item.product_obj.get_absolute_url }}">
                                                                {{ item.product_obj.title }}
                                                            </a>
                                                        </h3>
                                                    </td>
                                                    <td class="product-price">
                                                                <span class="product-price-wrapper">
                                                                    <span class="money">{{ item.product_obj.price|intcomma:False|translate_number }} {% trans '$' %}</span>
                                                                </span>
                                                    </td>
                                                    <td class="product-quantity">
                                                        <form class="d-flex" method="POST"
                                                              action="{% url 'cart:cart_add' item.product_obj.id %}">
                                                            {% csrf_token %}
                                                            <div class="quantity">
                                                                <input
                                                                        type="number"
                                                                        class="quantity-input"
                                                                        name="quantity"
                                                                        id="qty-1"
                                                                        value="{{ item.quantity }}"
                                                                        min="1"
                                                                >
                                                            </div>
                                                            {{ item.product_update_quantity_form.inplace }}
                                                            <button class="small" type="submit"><i
                                                                    class="fa fa-refresh"></i></button>
                                                        </form>
                                                    </td>
                                                    <td class="product-total-price">
                                                                <span class="product-price-wrapper">
                                                                    <span class="money">{{ item.total_price|intcomma:False|translate_number }} {% trans '$' %}</span>
                                                                </span>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                {% else %}
                                    <p>{% trans 'Cart is Empty! Please add some products to the cart' %}</p>
                                    <a href="{% url 'product_list' %}">{% trans 'Go shopping' %}</a>
                                {% endif %}
                            </div>
                        </div>
                        {% if not cart.is_empty %}
                            <div class="row no-gutters border-top pt--20 mt--20">
                                <div class="col-sm-6 text-sm-right">
                                    <form action="{% url 'cart:cart_clear' %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="cart-form__btn">
                                            {% translate 'Empty Cart' %}
                                        </button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-collaterals">
                            <div class="cart-totals">
                                <h5 class="font-size-14 font-bold mb--15">مجموع</h5>
                                <div class="cart-calculator">
                                    {#                                        <div class="cart-calculator__item">#}
                                    {#                                            <div class="cart-calculator__item--head">#}
                                    {#                                                <span>مجموع</span>#}
                                    {#                                            </div>#}
                                    {#                                            <div class="cart-calculator__item--value">#}
                                    {#                                                <span>۳۴۶,۰۰۰ تومان</span>#}
                                    {#                                            </div>#}
                                    {#                                        </div>#}
                                    <div class="cart-calculator__item order-total">
                                        <div class="cart-calculator__item--head">
                                            <span>جمع کل</span>
                                        </div>
                                        <div class="cart-calculator__item--value">
                                                <span class="product-price-wrapper">
                                                    <span class="money">{{ cart.get_total_price|intcomma:False|translate_number }} {% translate '$' %}</span>
                                                </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'order_create' %}"
                               class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                {% translate 'Checkout' %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Wrapper Start -->
{% endblock %}

cart/templates/cart/cart_sidebar.html
{% load i18n %}

<!-- Mini Cart Start -->
<aside class="mini-cart" id="miniCart">
    <div class="mini-cart-wrapper">
        <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
        <div class="mini-cart-inner">
            <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">{% translate 'Cart' %}</h3>
            <div class="mini-cart__content">
                <ul class="mini-cart__list text-right">
                    {% for item in cart %}
                        <li class="mini-cart__product d-flex justify-content-between">
                            <div class="mini-cart__product__image">
                                <a href="#">
                                    <img src="assets/img/products/prod-1-100x100.jpg">
                                </a>
                            </div>
                            <div class="mini-cart__product__content pt-2">
                                <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                    <a href="#">{{ item.product_obj.title }}</a>
                                    <a href="#" class="">
                                        &#10060;
                                    </a>
                                </span>
                                <span class="mini-cart__product__quantity">
                                    <span>{{ item.product_obj.price }}</span> &#215; <span>{{ item.quantity }}</span>
                                </span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div class="mini-cart__total">
                    <span>{% translate 'Total' %}</span>
                    <span class="amount"> {{ cart.get_total_price }} {% translate '$' %}</span>
                </div>
                <div class="mini-cart__buttons">
                    <a href="{% url 'cart:cart_detail' %}"
                       class="btn btn-fullwidth btn-bg-sand mb--20">{% translate 'Go to cart' %}</a>
                    {#                    {% if not cart.is_empty %}#}
                    {#                        <a href="{% url 'order_create' %}"#}
                    {#                           class="btn btn-fullwidth btn-bg-sand">{% translate 'Checkout' %}</a>#}
                    {#                    {% endif %}#}
                </div>
            </div>
        </div>
    </div>
</aside>
<!-- Mini Cart End -->

pages/templates/pages/aboutus.html
{% extends '_base.html' %}

{% block content %}
    <h1>About us</h1>
{% endblock %}

products/templates/products/product_list.html
{% extends '_base.html' %}

{% block content %}

    <!-- Main Wrapper Start -->
    <div class="wrapper">
        <!-- Main Content Wrapper Start -->
        <div class="main-content-wrapper container-fluid">
            <div class="shop-page-wrapper shop-fullwidth">
                <div class="container">
                    <div class="row mb--50">
                        <div class="col-12">
                            <div class="shop-toolbar">
                                <div class="container row align-items-center">
                                    <div class="col-lg-12 mb-md--50 mb-xs--10">
                                        <div class="shop-toolbar__left d-flex align-items-sm-center align-items-start flex-sm-row flex-column">
                                            <p class="product-pages">نمایش ۱-۲۰ از ۴۹</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container-fluid shop-products">
                    <div class="row">
                        <div class="col-12">
                            <div class="tab-content" id="product-tab-content">
                                <div class="tab-pane fade show active" id="nav-all">
                                    <div class="row xxl-block-grid-6 grid-space-20">
                                        {% for product in products %}
                                            <div class="col-xl-3 col-md-4 col-sm-6 mb--50">
                                                <div class="ShoppingYar-product">
                                                    <div class="product-inner">
                                                        <figure class="product-image">
                                                            <a href="{{ product.get_absolute_url }}">
                                                                {% if product.image %}
                                                                    <img src="{{ product.image.url }}"
                                                                         alt="Products">
                                                                {% endif %}
                                                            </a>
                                                            <div class="ShoppingYar-product-action">
                                                                <div class="product-action d-flex">
                                                                    <a href="wishlist.html" class="action-btn">
                                                                        <i class="flaticon flaticon-like"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <span class="product-badge">تخفیف ویژه</span>
                                                        </figure>
                                                        <div class="product-info">
                                                            <h3 class="product-title mb--15">
                                                                <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                                            </h3>
                                                            <div class="product-price-wrapper mb--30">
                                                                <span class="money">{{ product.price }} تومان</span>
                                                            </div>
                                                            <a href="{{ product.get_absolute_url }}"
                                                               class="btn btn-small btn-bg-sand btn-color-dark px-3">اضافه
                                                                کردن به سبد خرید</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <nav class="pagination-wrap mt--35 mt-md--25 pb-5">
                                <ul class="pagination">
                                    <li><a href="#" class="next page-number"><i
                                            class="fa fa-angle-double-right"></i></a></li>
                                    <li><span class="current page-number">1</span></li>
                                    <li><a href="#" class="page-number">2</a></li>
                                    <li><a href="#" class="page-number">3</a></li>
                                    <li><a href="#" class="prev page-number"><i class="fa fa-angle-double-left"></i></a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Content Wrapper Start -->

        <!-- Footer Start-->
        <footer class="footer">
            <div class="footer-top bg-color ptb--50" data-bg-color="#f6f6f6">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-9 text-center">
                            <div class="footer-widget mb--50">
                                <div class="textwidget">
                                    <img src="assets/img/codingyar_logo.png" alt="Logo">
                                </div>
                            </div>
                            <div class="footer-widget mb--50 pb--1">
                                <ul class="footer-menu">
                                    <li><a href="">درباره ما</a></li>
                                    <li><a href="">قوانین و مقررات</a></li>
                                    <li><a href="">تماس با ما</a></li>
                                </ul>
                            </div>
                            <div class="footer-widget">
                                Codingyar.com © | all rights reserved
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer End-->

        <!-- Search form Popup Start -->
        <div class="searchform__popup" id="searchForm">
            <a href="#" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="searchform__body">
                <p>در باکس زیر عبارت خود را وارد کنید</p>
                <form class="searchform">
                    <input type="text" name="popup-search" id="popup-search" class="searchform__input"
                           placeholder="جستجو در بین محصولات...">
                    <button type="submit" class="searchform__submit"><i
                            class="flaticon flaticon-magnifying-glass-icon"></i></button>
                </form>
            </div>
        </div>
        <!-- Search form Popup End -->

        {% include 'cart/cart_sidebar.html' %}

        <!-- Global Overlay Start -->
        <div class="ShoppingYar-global-overlay"></div>
        <!-- Global Overlay End -->

    </div>
    <!-- Main Wrapper End -->

{% endblock %}

templates/home.html
{% extends '_base.html' %}

{% block page_title %}
    Home Page
{% endblock %}

{% block content %}
    <h1>Home Page</h1>
{% endblock %}

templates/topheader.html
{% load i18n %}

<div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                    <h1 class="page-title">{{ header_name }}</h1>
                </div>
            </div>
        </div>
    </div>
</div>